import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Styles.module.scss'

import Navbar from '../components/navbar/index'
import Intro from '../components/hero/intro'
import Portfolio from '../components/hero/portfolio'
import About from '../components/hero/about'
import Contact from '../components/hero/contact'
import Skills from '../components/hero/skills'
import { useEffect } from 'react'
import { screenReveal } from '../animation/globalAnimation'
import Transition from '../components/hero/transition'
import { scrollToSection } from '../animation/navbarAnimation'



const Home: NextPage = () => {
  useEffect(() => {
    //Use of gsap to smooth reload blink screen.
    scrollToSection('#intro');
    screenReveal();
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition/>
      <Navbar />
      <main className={styles.main}>
        <section  id="intro">
          <Intro/>
        </section>
        <section>
          <About/>
        </section>
        <section>
          <Skills />
        </section>
        <section>
          <Portfolio/>
        </section>
        <section>
          <Contact/>
        </section>
      </main>
    </div>
  )
}

export default Home
