import type { NextPage } from 'next'
import {useEffect, useState} from 'react'
import gsap from 'gsap'
import Image from 'next/image'
import style from '../styles/Home.module.scss'
import theme from '../styles/Theme.module.scss'
import airplane from '../public/contatc_cta_dark.png'
import PortfolioHead from '../components/head/head'
import Navbar from '../components/navbar/navbar'
import Intro from '../components/hero/intro'
import AboutMe from '../components/hero/about'
import Skills from '../components/hero/skills'
import Portfolio from '../components/hero/portfolio'
import Contact from '../components/hero/contact'

const Home: NextPage = () => {
  const [isdarkMode, setDarkMode] = useState<boolean>(false);
  const [screenDimension, setDimension] = useState({'width':0, 'height':0});

  useEffect(() =>{
    const minDimension=(dim1:number, dim2:number)=>{
      return Math.min(dim1, dim2)
    }
    setDimension(
      // Set img dimension in a responsiveness manner 
      // according to the width of the screen 
      // Cap at 1500px
      {
        'width':minDimension(1500, window.innerWidth), 
        'height': minDimension(1500, window.innerWidth )
      }
    );
    console.log(screenDimension);
    gsap.to("body", {
      duration: 1,
      css:{visibility: "visible"}
    });
  },[])

  return (
    <>
      <div className={`${style.container} ${isdarkMode? theme.container_bgdark : theme.container_bglight}`}>
        <PortfolioHead/>
        <main className={style.main}>
          <Navbar isdarkMode={isdarkMode} setDarkMode={setDarkMode}/>
          {/* <div className={`${style.hero}`}> */}
            <Intro isdarkMode={isdarkMode} screenDimension={screenDimension}/>
            <AboutMe isdarkMode={isdarkMode} screenDimension={screenDimension}/>
            <Skills isdarkMode={isdarkMode}/>
            <Portfolio isdarkMode={isdarkMode}/>
            <Contact isdarkMode={isdarkMode}/>
          {/* </div> */}
        </main>
      </div>
    </>
  )
}

export default Home


// const DefaultNextindex=()=>{
//   return(
//     <>
//       <div className={styles.container}>
//         <Head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main className={styles.main}>
//           <h1 className={styles.title}>
//             Welcome to <a href="https://nextjs.org">Next.js!</a>
//           </h1>
//           <Image src={airplane} alt="test" width={150} height={150} />
//           <p className={styles.description}>
//             Get started by editing{' '}
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>

//           <div className={styles.grid}>
//             <a href="https://nextjs.org/docs" className={styles.card}>
//               <h2>Documentation &rarr;</h2>
//               <p>Find in-depth information about Next.js features and API.</p>
//             </a>

//             <a href="https://nextjs.org/learn" className={styles.card}>
//               <h2>Learn &rarr;</h2>
//               <p>Learn about Next.js in an interactive course with quizzes!</p>
//             </a>

//             <a
//               href="https://github.com/vercel/next.js/tree/master/examples"
//               className={styles.card}
//             >
//               <h2>Examples &rarr;</h2>
//               <p>Discover and deploy boilerplate example Next.js projects.</p>
//             </a>

//             <a
//               href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               className={styles.card}
//             >
//               <h2>Deploy &rarr;</h2>
//               <p>
//                 Instantly deploy your Next.js site to a public URL with Vercel.
//               </p>
//             </a>
//           </div>
//         </main>

//         <footer className={styles.footer}>
//           <a
//             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             Powered by{' '}
//             <span className={styles.logo}>
//               <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//             </span>
//           </a>
//         </footer>
//       </div>
//     </>
//   )
// };